name: Initial template changes
on: 
  create:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with: 
        files: '["README.md","package.json"]'
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        USER_OR_ORG: ${{ github.repository_owner }}
        DESC: ${{ github.event.repository.description }}
    - name: Update dependencies
      run: |
        npm install --save-dev denoify
        npm install --save-dev typescript
        npm install --save-dev evt
        rm package-lock.json
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "action"
        git commit -am "woosh, no longer a template, it is now ${{ github.event.repository.name }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
    - name: Create master branch
      run: |
        git branch master
        git checkout master
        git push origin master
      


