on:
  repository_dispatch:
    types: publish

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Update CHANGELOG.md
      if: ${{ !!github.event.client_payload.from_version }}
      uses: garronej/github_actions_toolkit@master
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        action_name: update_changelog
        owner: ${{github.repository_owner}}
        repo: ${{github.event.client_payload.repo}}
        branch_behind: master
        branch_ahead: dev
        commit_author_email: denoify_ci@github.com
        exclude_commit_from_author_names_json: '["denoify_ci"]'
    - name: Synchronize package.json  and package-lock.json version if needed.
      uses: garronej/github_actions_toolkit@master
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        action_name: sync_package_and_package_lock_version
        owner: ${{github.repository_owner}}
        repo: ${{github.event.client_payload.repo}}
        branch: dev
        commit_author_email: denoify_ci@github.com
      


  publish_npm:
    runs-on: ubuntu-latest
    needs: update_changelog
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install and build
      run: |
        npm install
        npm run build
    - run: npm run enable_short_import_path:deno
      env:
        DRY_RUN: "0"
    - name: Publishing on NPM ( you must create a secret called NPM_TOKEN. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets )
      #run: npm publish 
      run: ls -lR
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish_deno:
    runs-on: ubuntu-latest
    needs: publish_npm
    steps:
    - name: Remove master branch
      continue-on-error: true
      run: git push origin :master
    - name: Create the new master branch
      run: |
        git branch master
        git checkout master
        git push origin master
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install and build
      run: |
        npm install
        npm run build
    - run: npm run enable_short_import_path:deno
      env:
        DRY_RUN: "0"
    - name: Commit changes
      run: |
        git config --local user.email "denoify_ci@github.com"
        git config --local user.name "denoify_ci"
        git add -A
        git commit -am "Automatic structural changes for Deno"
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.PAT }}
        branch: master
    - name: Create Release
      uses: actions/create-release@v1.0.1 
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }} 
      with:
        tag_name: ${{ github.event.client_payload.to_version }}
        release_name: Release ${{ github.event.client_payload.to_version }}
        draft: false
        prerelease: false
  add_to_deno_land_third_party_module_register:
    runs-on: ubuntu-latest
    needs: publish_deno
    steps:
      - name: Create pull request on deno_website2
        run: echo TODO
