on: 
  create:
    branches:
      - dev

jobs:
  template_initialization:
    runs-on: ubuntu-latest
    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Test passing json 
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: ${{format('{{"from_version":"{0}","to_version":"{1}"}}',github.job,'0.0.1')}}


      - name: Checks that module name use _ instead of -
        if: contains(github.repository.name,'_')
        run: |
          echo "If you want to be able to publish on deno.land your module name must use lodash (_) in place of dashes (-) "
          sh -c "exit 1"
      - uses: actions/checkout@v2
      - name: Replace tokens in README.MD and package.json
        uses: cschleiden/replace-tokens@v1
        with: 
          files: '["README.md","package.json"]'
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          USER_OR_ORG: ${{ github.repository_owner }}
          DESC: ${{ github.event.repository.description }}
      - uses: actions/setup-node@v1
      - name: Update pre-configured dev dependencies
        run: |
          npm install --save-dev denoify
          npm install --save-dev typescript
          npm install --save-dev evt
          rm package-lock.json
      - name: Commit files
        run: |
          git config --local user.email "denoify_ci@github.com"
          git config --local user.name "denoify_ci"
          git commit -am "woosh, the template is now ${{ github.event.repository.name }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          branch: dev
