on: 
  create:
    branches:
      - dev

jobs:
  template_initialization:
    runs-on: ubuntu-latest
    steps:
      - name: Checks that module name use _ instead of -
        if: contains(github.repository.name,'_')
        run: |
          echo "If you want to be able to publish on deno.land your module name must use lodash (_) in place of dashes (-) "
          sh -c "exit 1"
      - uses: actions/checkout@v2
      - name: Replace tokens in README.MD and package.json
        uses: cschleiden/replace-tokens@v1
        with: 
          files: '["README.md","package.json"]'
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          USER_OR_ORG: ${{ github.repository_owner }}
          DESC: ${{ github.event.repository.description }}
      - uses: actions/setup-node@v1
      - name: Update pre-configured dev dependencies
        run: |
          npm install --save-dev denoify
          npm install --save-dev typescript
          npm install --save-dev evt
          rm package-lock.json
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "joseph@semasim.com"
          git config --local user.name "Joseph Garrone"
          git commit -am "woosh, the template is now ${{ github.event.repository.name }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
