on: create

jobs:
  template_initialization:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checks that module name use _ instead of -
        run: |
          if [ "$REPO_NAME_CONTAINS_DASHES" = "true" ]; then
            echo "Your module name should not contain dashes, you won't be allowed to publish on deno.land"
            echo "Please delete this repo and create a new one replacing all the occurrences of '-' by '_'"
            false
          fi
          true
        env: 
          REPO_NAME_CONTAINS_DASHES: ${{ contains(github.event.repository.name,'-') }}

      - uses: actions/checkout@v2
      - name: Replace tokens in README.MD and package.json
        uses: cschleiden/replace-tokens@v1
        with: 
          files: '["README.md","package.json"]'
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          USER_OR_ORG: ${{ github.repository_owner }}
          DESC: ${{ github.event.repository.description }}
      - uses: actions/setup-node@v1
      - name: Update pre-configured dev dependencies
        run: |
          npm install --save-dev denoify
          npm install --save-dev typescript
          npm install --save-dev evt
          rm package-lock.json
      - name: Remove this workflow, it only needs to be run once.
        run: rm .github/workflows/template_initialization.yaml
      - name: Commit files
        run: |
          git config --local user.email "denoify_ci@github.com"
          git config --local user.name "denoify_ci"
          git commit -am "woosh, the template is now ${{ github.event.repository.name }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          branch: dev
